music_genres_classification/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predictions.urls')),
]

predictions/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('predict_genre/', views.predict_genre, name='predict_genre'),
]

predictions/models.py
from django.db import models

# Create your models here.

predictions/forms.py
from django import forms

class MusicGenreForm(forms.Form):
    age = forms.IntegerField(label='Age', widget=forms.NumberInput(attrs={
        'class': 'block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-200 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 focus:ring-blue-300 focus:ring-opacity-40 dark:focus:border-blue-300 focus:outline-none focus:ring required',
        'placeholder': 'Your Age...',
        }))
    gender = forms.ChoiceField(label='Gender', choices=[(1, 'Male'), (0, 'Female')], 
                               widget=forms.Select(attrs={
                                   'class': 'block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-200 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 focus:ring-blue-300 focus:ring-opacity-40 dark:focus:border-blue-300 focus:outline-none focus:ring',
                                   
                                   }))

predictions/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .forms import MusicGenreForm
import joblib
import json

def index(request):
    form = MusicGenreForm()
    return render(request, 'index.html', {'form': form})

def predict_genre(request):
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        form = MusicGenreForm(request.POST)
        if form.is_valid():
            age = form.cleaned_data['age']
            gender = form.cleaned_data['gender']
            model = joblib.load('music-recommender.pkl')
            prediction = model.predict([[age, gender]])
            # Convert ndarray to a JSON serializable format
            prediction_json = prediction.tolist()  # Convert to Python list
            return JsonResponse({'result': prediction_json})
        else:
            return JsonResponse({'error': 'Form is not valid'}, status=400)
    else:
        return JsonResponse({'error': 'Invalid request method or not an AJAX request'}, status=405)

templates/base.html
{% load static %}

<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="icon"  href="/static/images/favicon.png">
  <link rel="stylesheet" href="/static/styles.css">
  <link rel="stylesheet" href="{% static 'src/styles.css' %}"> 

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
        {% block content %}
        {% endblock content %}
    </div>
</body>
<script src="/static/script.js"></script>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<!-- Navbar section -->
<section style="padding-top: 0;
  padding-bottom: 0.05rem;" class=" sticky top-0 z-30 bg-[#001524] opacity-90 bg-gradient-to-r from-[#001524] via-sky-400 to-[#001524] shadow-sm">
   <div class="bg-[#001524] h-20 py-5">
    <div class=" mx-auto max-w-7xl px-8 lg:px-8 sm:px-6">
      <div class="flex  items-center justify-between">
        <div class="flex items-start">
          <img src="/static/images/Logo_to_use.png" class="px-3 py-2 text-sm font-medium hidden lg:flex xl:flex" height="140" width="140" alt="Company Logo">
          <img src="/static/images/favicon.png" class="px-3 py-2 text-sm font-medium flex lg:hidden" height="60" width="60" alt="icon-logo">
        </div>
        <div class="flex items-center">
          <div class="flex space-x-4top-0">
            <img width="30" height="30" style="  filter: brightness(0) invert(1);"  src="/static/images/music.gif" alt="music logo"/>
          </div>
        </div>
        <div class="flex items-end">
          <div class="flex space-x-4">
            <a href="https://github.com/ericktek" class="mx-2 text-gray-600 transition-colors duration-300 dark:text-gray-300 hover:text-sky-900 dark:hover:text-gray-300" aria-label="Github">
              <svg class="w-8 h-8 fill-current" viewBox="0 0 24 24" fill="none"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                      d="M12.026 2C7.13295 1.99937 2.96183 5.54799 2.17842 10.3779C1.395 15.2079 4.23061 19.893 8.87302 21.439C9.37302 21.529 9.55202 21.222 9.55202 20.958C9.55202 20.721 9.54402 20.093 9.54102 19.258C6.76602 19.858 6.18002 17.92 6.18002 17.92C5.99733 17.317 5.60459 16.7993 5.07302 16.461C4.17302 15.842 5.14202 15.856 5.14202 15.856C5.78269 15.9438 6.34657 16.3235 6.66902 16.884C6.94195 17.3803 7.40177 17.747 7.94632 17.9026C8.49087 18.0583 9.07503 17.99 9.56902 17.713C9.61544 17.207 9.84055 16.7341 10.204 16.379C7.99002 16.128 5.66202 15.272 5.66202 11.449C5.64973 10.4602 6.01691 9.5043 6.68802 8.778C6.38437 7.91731 6.42013 6.97325 6.78802 6.138C6.78802 6.138 7.62502 5.869 9.53002 7.159C11.1639 6.71101 12.8882 6.71101 14.522 7.159C16.428 5.868 17.264 6.138 17.264 6.138C17.6336 6.97286 17.6694 7.91757 17.364 8.778C18.0376 9.50423 18.4045 10.4626 18.388 11.453C18.388 15.286 16.058 16.128 13.836 16.375C14.3153 16.8651 14.5612 17.5373 14.511 18.221C14.511 19.555 14.499 20.631 14.499 20.958C14.499 21.225 14.677 21.535 15.186 21.437C19.8265 19.8884 22.6591 15.203 21.874 10.3743C21.089 5.54565 16.9181 1.99888 12.026 2Z">
                  </path>
              </svg>
          </a>
          </div>
        </div>
    </div>
  </div>
   </div>
  </section>
<!-- End Navbar section -->
<!-- Feature section -->

<div class="relative sm:py-2 lg:py-8">
  <div class="bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] absolute from-sky-950  to-transparent rounded-full w-80 h-80 z-50 blur-3xl -left-2 -translate-x-1/4"> </div>
  </div>
  <!-- End Feature section -->
 <!-- hero section -->
 <section class=" mx-auto max-w-7xl px-8 body-font">
  <div class="container flex lg:flex-row flex-col gap-2 px-4 py-24">
    <div class="w-full lg:w-1/2 flex flex-col justify-center  pt-16">
          <h1 id="elementEl" 
          class=" sm:text-4xl text-3xl mb-4 font-bold bg-gradient-to-r  from-gray-50 via-sky-400 to-gray-100 text-transparent bg-clip-text">Music Recommendation 
      </h1>
      <p class="mb-8 leading-relaxed font-mono ">The model predicts by classifying age and gender. It utilizes a Decision Tree algorithm to categorize music based on age and gender.</p>
    <!--  Animation gif -->
      <div class="flex justify-center items-center">
        <img src="/static/images/hero-animate2.gif" class="w-64" height="300px" width="300px" alt="animation">
      </div>
    </div>
    <div style="padding-top: 0.05rem; padding-bottom: 0.05rem" class="relative w-full lg:w-1/2 lg:mt-0 bg-white rounded-md bg-gradient-to-r from-[#001524] via-sky-400 to-[#001524] ">

   <!-- Code demo card -->
    <div class="bg-[#081e2d] shadow-md drop-shadow-xl bg-none  shadow-sky-950 text-white p-4 rounded-md transition delay-150 duration-300 ease-in-out">
        <div class="flex px-3 mr-3 mt-2 justify-between items-center mb-4">
            <div 
            style="
            padding-top: 0.05rem;
            padding-bottom: 0.05rem;
            padding-left: 0.2rem;
            padding-right: 0.2rem"
            
            class="text-gray-400 shadow-sm rounded-lg bg-slate-900 bg-gradient-to-r from-[#001524] via-sky-400 to-[#001524] "> 
              <div
            
            class="border border-sky-400 border-t-0 border-b-0 bg-gradient-to-r rounded-lg from-[#001524] via-sky-950 to-[#001524] h-full w-full text-xs text-sky-500 p-1">Jupiter Notebook</div></div>
            <button class="code bg-gray-800 hover:bg-gray-700 text-gray-300 px-3 py-1 rounded-md text-xs" data-clipboard-target="#code">
        Copy
      </button>
        </div>
        <div style="height: 30rem; scrollbar-width: none; -ms-overflow-style: none;" class="overflow-auto" x-data>
  <pre id="code" class="text-gray-300">

    <span id="typer1" class="elementTyper"><code class="text-sky-500">import</code> pandas <code class="text-sky-500">as</code> pd</span>
    <code class="text-sky-500">from</code> sklearn.tree <code class="text-sky-500">import</code> DecisionTreeClassifier
    <code class="text-sky-500">from</code> sklearn.model_selection <code class="text-sky-500">import</code> train_test_split
    <code class="text-sky-500">from</code> sklearn.metrics <code class="text-sky-500">import</code> accuracy_score
    <span id="typer2" class="elementTyper"><code class="text-sky-500">from</code> sklearn.metrics <code class="text-sky-500">import</code> accuracy_score</span>

    # Load the dataset
    <span id="typer3" class="elementTyper">df = pd.read_csv('<code class="text-sky-500">'music-dataset'</code>')</span>
  
    X = df.drop(columns=[<code class="text-sky-500">'genre'</code>]) 
    y = df[<code class="text-sky-500">'genre'</code>]  
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=True)
    # Create and fit the model
    model = DecisionTreeClassifier()
    <span id="typer4" class="elementTyper">model.fit(X_train, y_train)</span>
  
    # Make prediction

    <span id="typer5" class="elementTyper">score =  accuracy_score(X_test,  prediction)</span>
    accuracy_score(y_test, y_pred)

    <span id="typer6" class="elementTyper"><code class="text-sky-500">Out[90]: 1.0 </code> </span>
  </pre>
        </div>
    </div>
  <!-- End Code demo card -->
  
</div>

    <!-- blur feature -->
<div class="relative -top-96 lg:-top-2 xl:-top-2 ">
  <div class="bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] absolute -rotate-45 from-sky-950  to-transparent blur-3xl rounded-sm w-56 h-96 z-50 -top-8 -right-2  -translate-x-1/4"> </div>
  </div>
</div>
</section>
<!-- End hero section -->

<!-- Form section -->
    <section class="relative bg-[url('/static/images/hero.gif')] bg-no-repeat bg-cover">
      <div class="absolute inset-0 backdrop-filter backdrop-blur-sm backdrop-brightness-80"></div>
      <div class=" bg-gradient-to-t from-[#001524] via-transparent to-[#001524]">
        <div class="relative z-10 max-w-lg p-6 mx-auto h-screen flex justify-center  items-center" >
        <div class=" p-6 rounded-md shadow-2xl shadow-[#001524] bg-white  dark:bg-gray-800">
          <h2 class="text-3xl py-4 flex items-center justify-center font-semibold font-mono text-gray-700 capitalize dark:text-white">Music Recommendation</h2>
          <p class="text-sm font-normal leading-relaxed text-gray-300 capitalize ">Age is between 20 - 35. Out of boundary lower Prediction Accuracy</p>
          <form id="music-form" method="post"> 
            {% csrf_token %}
            <div class="flex flex-col gap-6 mt-4">
              <div id="alert-message"></div> 

              {{ form.as_p }}

            </div>
            <div class="flex justify-end mt-6">
                <button type="button" id="submit-btn" class="px-8 py-2.5 leading-5 text-white transition-colors duration-300 transform bg-gray-700 rounded-md hover:bg-gray-600 focus:outline-none focus:bg-gray-600">Make Prediction</button>
            </div>
        </form>
                
        <div id="result">
            {% if result %}
                <h1 class="text-white pt-4">You Like: <span class="text-sky-500">{{ result }}</span></h1>
            {% endif %}
        </div>
        
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <script>
      // Preventing page reloading
      $(document).ready(function() {
        $('#submit-btn').click(function() {
        var formData = new FormData($('#music-form')[0]);

        var ageValue = $('#id_age').val().trim();
        if (ageValue === '') {
          $('#alert-message').html('<div class="alert alert-danger text-red-500" role="alert">Please! Age field should not be empty  </div>');
            $('#result').html('')
            return; // Stop further execution
        }

        $.ajax({
            url: '/predict_genre/',
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function(response) {
                $('#music-form').trigger('reset');
                $('#alert-message').html('');
                $('#result').html('<h1 class="text-white pt-4">You Like: <span class="text-sky-500">' + response.result + '</span></h1>');
            },
            error: function(xhr, status, error) {
                console.error('Error:', error);
            }
        });
    });
});

        </script>
        
        
      
      </div>
    </div>
    </section>
    <!-- Feature section -->

<div class="relative sm:py-2 lg:py-8">
  <div class="bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] absolute from-sky-950  to-transparent rounded-lg w-96 p-32 rotate-45 h-32 z-50 blur-3xl -right-16 -bottom-96  md:-bottom-80 lg:-bottom-80 -translate-x-1/2"> </div>
  </div>
  <!-- End Feature section -->

          <footer class="mx-auto max-w-7xl p-4 sm:p-6">
              <div class="container mx-auto flex px-5 md:flex-row flex-col items-center">
                <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
                  <img src="/static/images/join-us.svg" width="24rem" height="24rem" class="mr-3 h-96 w-96" alt="FlowBite Logo" />
                </div>
                <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
                  <h1 class="title-font sm:text-4xl font-sans text-3xl mb-4 font-medium text-gray-100">Get in touch
                  </h1>
                  <p class="mb-8 leading-relaxed font-mono">
                    
                    Join ericktek's team to explore machine learning and software development. All skill levels are welcome in our collaborative and innovative environment. Let's build the future together!
                  
                  
                  </p>
                  <div class="flex justify-center">
                    <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none rounded text-lg">Contact</button>
                    <button class="ml-4 inline-flex text-gray-100 border border-indigo-500 py-1 items-center  justify-center xl:py-2 xl:px-6 lg:py-2 lg:px-6 px-2 focus:outline-none  rounded tex-xs lg:text-lg xl:text-lg">0769 500 360</button>
                  </div>
                </div>
              </div>
              <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
                    <div class="flex items-center justify-center text-sm text-gray-500 text-center dark:text-gray-400">&copy; 2024 ericktek. All Rights Reserved
                    </div>
                    
        </footer>      
  </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>
<script>
  new ClipboardJS('.code');
</script>
   </script>
{% endblock %}